/**
 * Copy `deno doc --html` output from ../docs/api/ into ./public/api/ so Astro
 * picks it up as static assets. Source is generated by `deno task doc` in the
 * repo root and is gitignored.
 */
import { cp, mkdir, rm, stat } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const src = resolve(here, "../../docs/api");
const dest = resolve(here, "../public/api");

const srcInfo = await stat(src).catch(() => null);
if (!srcInfo?.isDirectory()) {
  console.warn(
    `[copy-api] ${src} not found. Run 'deno task doc' in the repo root first.`,
  );
  process.exit(0);
}

await rm(dest, { recursive: true, force: true });
await mkdir(dest, { recursive: true });
await cp(src, dest, { recursive: true });
console.log(`[copy-api] copied ${src} -> ${dest}`);
